version: '2'

services:
  mysql:
      image: 'mysql'
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_HOST: mysql
        MYSQL_DATABASE: Tez
      ports:
        - 3306:3306
      networks:
        - laravel
  myapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mysql
    networks:
        - laravel
  phpmyadmin:
      image: 'phpmyadmin'
      restart: 'always' 
      ports:
        - 8083:80
      environment:
        - PMA_ARBITRARY=1
      networks:
        - laravel
networks:
    laravel:
        driver: bridge